### ISSUE TITLE
Adding functionality: Add min/max/std (possibly some covs too)

### ISSUE THREAD

**Issue by znesic** [June-Skeeter/EddyPro_API#5]
Hi June, I was going to send an email, but thought that this is probably a better way to do it.

I see from your README that you calculate means of all GHG input columns. It would be good to also calculate min, max, and std for all the input variables too. I have it on my list to do that in Matlab but I think that it makes more sense to make it part of this API.

If it doesn't fit here let me know and I'll do it in Matlab.

**Comment by June-Skeeter** [comment]
Good idea.  Its fairly straightforward to add the functionality to calculate these statistics as well :)
